#**第一題**

# 輸入層:6個神經元


In [2]:
import numpy as np

In [3]:
x = np.array([0.0, 2.0, 4.0, 6.0, 8.0, 10.0])

print("x =", x)
print("x.shape =", x.shape)

x = [ 0.  2.  4.  6.  8. 10.]
x.shape = (6,)


# 第一隱藏層:5個神經元

激發函數使用ReLU

In [11]:
def relu(x):
    return np.maximum(0, x)

In [10]:
W1 = np.array([
    [0.5, 1.0, 2.0, 0.4, 1.5],
    [0.2, 0.5, 2.4, 1.5, 1.6],
    [0.4, 0.5, 1.5, 1.6, 0.8],
    [0.5, 1.5, 2.6, 0.4, 0.6],
    [0.4, 0.6, 0.2, 1.8, 0.5],
    [0.6, 0.2, 0.8, 0.4, 1.0]
])
b1 = np.array([1.0, 3.0, 2.0, 7.0, 6.0])

print("W1 =", W1)
print("b1 =", b1)
print("W1.shape =", W1.shape)
print("b1.shape =", b1.shape)
print("W1參數個數 =", W1.size)
print("b1參數個數 =", b1.size)


W1 = [[0.5 1.  2.  0.4 1.5]
 [0.2 0.5 2.4 1.5 1.6]
 [0.4 0.5 1.5 1.6 0.8]
 [0.5 1.5 2.6 0.4 0.6]
 [0.4 0.6 0.2 1.8 0.5]
 [0.6 0.2 0.8 0.4 1. ]]
b1 = [1. 3. 2. 7. 6.]
W1.shape = (6, 5)
b1.shape = (5,)
W1參數個數 = 30
b1參數個數 = 5


三個神經元調整的加權總合: z = X．W + b

In [12]:
z1 = np.dot(x, W1) + b1
h1 = relu(z1)
print("z1 =", z1)
print("z1.shape =", z1.shape)

print("h1 =", h1)
print("h1.shape =", h1.shape)

z1 = [15.2 21.8 38.  37.2 30. ]
z1.shape = (5,)
h1 = [15.2 21.8 38.  37.2 30. ]
h1.shape = (5,)


#第二隱藏層:4個神經元

In [13]:
W2 = np.array([
    [0.5, 1.0, 2.0, 0.4],
    [0.2, 0.5, 2.4, 1.5],
    [0.4, 0.5, 1.5, 1.6],
    [0.5, 1.5, 2.6, 0.4],
    [0.4, 0.6, 0.2, 1.8],
])

b2 = np.array([1.0, 3.0, 2.0, 7.0])

print("W2 =", W2)
print("b2 =", b2)
print("W2.shape =", W2.shape)
print("b2.shape =", b2.shape)
print("W2參數個數 =", W2.size)
print("b2參數個數 =", b2.size)

W2 = [[0.5 1.  2.  0.4]
 [0.2 0.5 2.4 1.5]
 [0.4 0.5 1.5 1.6]
 [0.5 1.5 2.6 0.4]
 [0.4 0.6 0.2 1.8]]
b2 = [1. 3. 2. 7.]
W2.shape = (5, 4)
b2.shape = (4,)
W2參數個數 = 20
b2參數個數 = 4


三個神經元調整的加權總合: z = X．W + b

激發函數使用ReLU

In [14]:
z2 = np.dot(h1, W2) + b2
h2 = relu(z2)

print("z2 =", z2)
print("z2.shape =", z2.shape)

print("h2 =", h2)
print("h2.shape =", h2.shape)

z2 = [ 58.76 121.9  244.44 175.46]
z2.shape = (4,)
h2 = [ 58.76 121.9  244.44 175.46]
h2.shape = (4,)


#第三隱藏層:4個神經元


In [15]:
W3 = np.array([
    [0.5, 1.0, 2.0, 0.4],
    [0.2, 0.5, 2.4, 1.5],
    [0.4, 0.5, 1.5, 1.6],
    [0.5, 1.5, 2.6, 0.4],
])

b3 = np.array([1.0, 3.0, 2.0, 7.0])

print("W3 =", W3)
print("b3 =", b3)
print("W3.shape =", W3.shape)
print("b3.shape =", b3.shape)
print("W3參數個數 =", W3.size)
print("b3參數個數 =", b3.size)

W3 = [[0.5 1.  2.  0.4]
 [0.2 0.5 2.4 1.5]
 [0.4 0.5 1.5 1.6]
 [0.5 1.5 2.6 0.4]]
b3 = [1. 3. 2. 7.]
W3.shape = (4, 4)
b3.shape = (4,)
W3參數個數 = 16
b3參數個數 = 4


激發函數使用sigmoid

In [16]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

三個神經元調整的加權總合: z = X．W + b

In [17]:
z3 = np.dot(h2, W3) + b3
h3 = sigmoid(z3)

print("z3 =", z3)
print("z3.shape =", z3.shape)

print("h3 =", h3)
print("h3.shape =", h3.shape)

z3 = [ 240.266  508.12  1234.936  674.642]
z3.shape = (4,)
h3 = [1. 1. 1. 1.]
h3.shape = (4,)


#輸出層:3個神經元

In [18]:
W4 = np.array([
    [0.5, 1.0, 2.0],
    [0.2, 0.5, 2.4],
    [0.4, 0.5, 1.5],
    [0.5, 1.5, 2.6],
])

b4 = np.array([1.0, 3.0, 2.0])

print("W4 =", W4)
print("b4 =", b4)
print("W4.shape =", W4.shape)
print("b4.shape =", b4.shape)
print("W4參數個數 =", W4.size)
print("b4參數個數 =", b4.size)

W4 = [[0.5 1.  2. ]
 [0.2 0.5 2.4]
 [0.4 0.5 1.5]
 [0.5 1.5 2.6]]
b4 = [1. 3. 2.]
W4.shape = (4, 3)
b4.shape = (3,)
W4參數個數 = 12
b4參數個數 = 3


激發函數使用Softmax

In [19]:
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

三個神經元調整的加權總合: z = X．W + b

In [20]:
z4 = np.dot(h3, W4) + b4
y_hat = softmax(z4)

print("z4 =", z4)
print("z4.shape =", z4.shape)

print("y_hat =", y_hat)
print("y_hat.shape =", y_hat.shape)
print("y_hat 機率總和 =", np.sum(y_hat))

z4 = [ 2.6  6.5 10.5]
z4.shape = (3,)
y_hat = [3.63942767e-04 1.79796640e-02 9.81656393e-01]
y_hat.shape = (3,)
y_hat 機率總和 = 1.0


結果說明：因為輸出層有三個神經元，且使用softmax，所以，計算結果y_hat為三個機率值，分別代表：X屬於第1種類別的機率(3.63942767e-04)與屬於第2種類別的機率(1.79796640e-02)，以及屬於第3種類別的機率(9.81656393e-01)

衡量 y_hat與y的誤差值

In [21]:
# cross_entropy_error用來計算神經網路計算出的結果y_hat與真正的結果y之間的誤差
def cross_entropy_error(y_hat, y):
    return -np.sum(y * np.log(y_hat + 1e-7))

In [22]:
#y代表是X的真正的結果，也就是，x屬於第3種類別的機率為1，屬於其他類別的機率為0
y = np.array([0, 0, 1])

In [23]:
np.log(y_hat + 1e-7)

array([-7.91823921, -4.01850838, -0.01851384])

In [24]:
y*np.log(y_hat + 1e-7)

array([-0.        , -0.        , -0.01851384])

In [25]:
-np.sum(y * np.log(y_hat + 1e-7))

np.float64(0.018513835059155836)

In [26]:
cross_entropy_error(y_hat, y)

np.float64(0.018513835059155836)

#**第二題**

#DNN

In [27]:
def dnn(x):
    z1 = np.dot(x, W1) + b1
    h1 = relu(z1)

    z2 = np.dot(h1, W2) + b2
    h2 = relu(z2)

    z3 = np.dot(h2, W3) + b3
    h3 = sigmoid(z3)

    z4 = np.dot(h3, W4) + b4
    y_hat = softmax(z4)

    return y_hat

y_hat_dnn = dnn(x)

print("原本計算的 y_hat =", y_hat)
print("dnn(x)的結果 =", y_hat_dnn)
print("兩者是否相同 =", np.allclose(y_hat, y_hat_dnn))

原本計算的 y_hat = [3.63942767e-04 1.79796640e-02 9.81656393e-01]
dnn(x)的結果 = [3.63942767e-04 1.79796640e-02 9.81656393e-01]
兩者是否相同 = True


# gradio套件

In [28]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


讀入基本套件

In [29]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [31]:
import gradio as gr

def predict(x1, x2, x3, x4, x5, x6):
    x = np.array([x1, x2, x3, x4, x5, x6], dtype=float)
    y_hat = dnn(x)
    category = int(np.argmax(y_hat) + 1)
    return category


demo = gr.Interface(
    fn=predict,
    inputs=[
        gr.Number(label="特徵值1"),
        gr.Number(label="特徵值2"),
        gr.Number(label="特徵值3"),
        gr.Number(label="特徵值4"),
        gr.Number(label="特徵值5"),
        gr.Number(label="特徵值6")
    ],
    outputs=gr.Number(label="y_hat當中機率最高的類別"),
    description="輸入 6 個特徵值"
)

demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://3180132b9b38bda91f.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
