<a href="https://colab.research.google.com/github/3B232056/2026_DL_hws/blob/main/hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#作業2：多隱藏層的全連接神經網路可批次學習

In [1]:
import numpy as np

自行產生五個x各自的6個特徵值及其真實結果y

In [3]:
X = np.array([
    [0, 2, 4, 6, 8, 10],
    [1, 3, 5, 7, 9, 0],
    [3, 6, 5, 9, 0, 1],
    [5, 3, 0, 7, 9, 8],
    [2, 1, 6, 3, 8, 5]
])

y = np.array([
    [1, 0, 0],
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0],
    [0, 1, 0]
])

print("X =", X)
print("X.shape =", X.shape)

print("y =", y)
print("y.shape =", y.shape)

X = [[ 0  2  4  6  8 10]
 [ 1  3  5  7  9  0]
 [ 3  6  5  9  0  1]
 [ 5  3  0  7  9  8]
 [ 2  1  6  3  8  5]]
X.shape = (5, 6)
y = [[1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]]
y.shape = (5, 3)


第一層權重 W1 與偏值 b1

In [8]:
W1 = np.array([
    [0.5, 1.0, 2.0, 0.4, 1.5],
    [0.2, 0.5, 2.4, 1.5, 1.6],
    [0.4, 0.5, 1.5, 1.6, 0.8],
    [0.5, 1.5, 2.6, 0.4, 0.6],
    [0.4, 0.6, 0.2, 1.8, 0.5],
    [0.6, 0.2, 0.8, 0.4, 1.0]
])
b1 = np.array([1.0, 3.0, 2.0, 7.0, 6.0])

print("W1 =", W1)
print("b1 =", b1)
print("X.shape =", X.shape)
print("W1.shape =", W1.shape)
print("b1.shape =", b1.shape)

W1 = [[0.5 1.  2.  0.4 1.5]
 [0.2 0.5 2.4 1.5 1.6]
 [0.4 0.5 1.5 1.6 0.8]
 [0.5 1.5 2.6 0.4 0.6]
 [0.4 0.6 0.2 1.8 0.5]
 [0.6 0.2 0.8 0.4 1. ]]
b1 = [1. 3. 2. 7. 6.]
X.shape = (5, 6)
W1.shape = (6, 5)
b1.shape = (5,)


定義 ReLU

In [6]:
def relu(x):
    return np.maximum(0, x)

In [7]:
Z1 = np.dot(X, W1) + b1
H1 = relu(Z1)

print("Z1 =", Z1)
print("Z1.shape =", Z1.shape)
print("H1 =", H1)
print("H1.shape =", H1.shape)

Z1 = [[15.2 21.8 38.  37.2 30. ]
 [11.2 23.9 38.7 38.9 25. ]
 [10.8 25.2 54.1 29.2 30.5]
 [16.  27.  45.6 35.7 35. ]
 [12.3 18.8 30.8 36.5 26.2]]
Z1.shape = (5, 5)
H1 = [[15.2 21.8 38.  37.2 30. ]
 [11.2 23.9 38.7 38.9 25. ]
 [10.8 25.2 54.1 29.2 30.5]
 [16.  27.  45.6 35.7 35. ]
 [12.3 18.8 30.8 36.5 26.2]]
H1.shape = (5, 5)


第二層權重 W2 與偏值 b2

In [9]:
W2 = np.array([
    [0.5, 1.0, 2.0, 0.4],
    [0.2, 0.5, 2.4, 1.5],
    [0.4, 0.5, 1.5, 1.6],
    [0.5, 1.5, 2.6, 0.4],
    [0.4, 0.6, 0.2, 1.8],
])

b2 = np.array([1.0, 3.0, 2.0, 7.0])


print("W2 =", W2)
print("b2 =", b2)
print("H1.shape =", H1.shape)
print("W2.shape =", W2.shape)
print("b2.shape =", b2.shape)

W2 = [[0.5 1.  2.  0.4]
 [0.2 0.5 2.4 1.5]
 [0.4 0.5 1.5 1.6]
 [0.5 1.5 2.6 0.4]
 [0.4 0.6 0.2 1.8]]
b2 = [1. 3. 2. 7.]
H1.shape = (5, 5)
W2.shape = (5, 4)
b2.shape = (4,)


In [10]:
Z2 = np.dot(H1, W2) + b2
H2 = relu(Z2)

print("Z2 =", Z2)
print("Z2.shape =", Z2.shape)
print("H2 =", H2)
print("H2.shape =", H2.shape)

Z2 = [[ 58.76 121.9  244.44 175.46]
 [ 56.31 118.85 245.95 169.81]
 [ 59.88 115.55 247.25 202.26]
 [ 64.49 129.85 267.02 204.14]
 [ 51.96 110.57 218.06 151.16]]
Z2.shape = (5, 4)
H2 = [[ 58.76 121.9  244.44 175.46]
 [ 56.31 118.85 245.95 169.81]
 [ 59.88 115.55 247.25 202.26]
 [ 64.49 129.85 267.02 204.14]
 [ 51.96 110.57 218.06 151.16]]
H2.shape = (5, 4)


第三層權重 W3 與偏值 b3

In [12]:
W3 = np.array([
    [0.5, 1.0, 2.0, 0.4],
    [0.2, 0.5, 2.4, 1.5],
    [0.4, 0.5, 1.5, 1.6],
    [0.5, 1.5, 2.6, 0.4],
])

b3 = np.array([1.0, 3.0, 2.0, 7.0])

print("W3 =", W3)
print("b3 =", b3)
print("H2.shape =", H2.shape)
print("W3.shape =", W3.shape)
print("b3.shape =", b3.shape)

W3 = [[0.5 1.  2.  0.4]
 [0.2 0.5 2.4 1.5]
 [0.4 0.5 1.5 1.6]
 [0.5 1.5 2.6 0.4]]
b3 = [1. 3. 2. 7.]
H2.shape = (5, 4)
W3.shape = (4, 4)
b3.shape = (4,)


定義 Sigmoid

In [13]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [14]:
Z3 = np.dot(H2, W3) + b3
H3 = sigmoid(Z3)

print("Z3 =", Z3)
print("Z3.shape =", Z3.shape)
print("H3 =", H3)
print("H3.shape =", H3.shape)

Z3 = [[ 240.266  508.12  1234.936  674.642]
 [ 236.21   496.425 1210.291  669.243]
 [ 254.08   547.67  1295.831  680.781]
 [ 268.093  572.135 1373.914  736.459]
 [ 211.898  446.015 1091.394  602.999]]
Z3.shape = (5, 4)
H3 = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
H3.shape = (5, 4)


第四層(輸出層) 權重 W4與偏值 b4，計算 y_hat

In [15]:
W4 = np.array([
    [0.5, 1.0, 2.0],
    [0.2, 0.5, 2.4],
    [0.4, 0.5, 1.5],
    [0.5, 1.5, 2.6],
])

b4 = np.array([1.0, 3.0, 2.0])

print("W4 =", W4)
print("b4 =", b4)
print("H3.shape =", H3.shape)
print("W4.shape =", W4.shape)
print("b4.shape =", b4.shape)

W4 = [[0.5 1.  2. ]
 [0.2 0.5 2.4]
 [0.4 0.5 1.5]
 [0.5 1.5 2.6]]
b4 = [1. 3. 2.]
H3.shape = (5, 4)
W4.shape = (4, 3)
b4.shape = (3,)


定義Softmax

In [16]:
def softmax(x):
    x = x - np.max(x, axis=-1, keepdims=True)
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

In [21]:
Z4 = np.dot(H3, W4) + b4
y_hat = softmax(Z4)

print("Z4 =", Z4)
print("Z4.shape =", Z4.shape)
print("y_hat =", y_hat)
print("y_hat.shape =", y_hat.shape)

Z4 = [[ 2.6  6.5 10.5]
 [ 2.6  6.5 10.5]
 [ 2.6  6.5 10.5]
 [ 2.6  6.5 10.5]
 [ 2.6  6.5 10.5]]
Z4.shape = (5, 3)
y_hat = [[3.63942767e-04 1.79796640e-02 9.81656393e-01]
 [3.63942767e-04 1.79796640e-02 9.81656393e-01]
 [3.63942767e-04 1.79796640e-02 9.81656393e-01]
 [3.63942767e-04 1.79796640e-02 9.81656393e-01]
 [3.63942767e-04 1.79796640e-02 9.81656393e-01]]
y_hat.shape = (5, 3)


cross_entropy_error計算y_hat和y誤差值的平均

定義Cross entropy error (交叉熵誤差)

In [22]:
def cross_entropy_error(y_hat, t):
    if y_hat.ndim == 1:
        t = t.reshape(1, t.size)
        y_hat = y_hat.reshape(1, y_hat.size)

    batch_size = y_hat.shape[0]

    return -np.sum(t * np.log(y_hat + 1e-7)) / batch_size

y_hat和y誤差值的平均

In [23]:
cross_entropy_error(y_hat, y)

np.float64(4.778401799530255)